name = "voice-memo-task-manager"
main = "src/index.ts"
compatibility_date = "2024-10-22"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "task_manager"
database_id = "local-dev"

# R2 bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "voice-memos"
jurisdiction = "eu"
preview_bucket_name = "voice-memos-preview"
